# Generated by Django 5.0.14 on 2026-03-10 15:59

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('limit', models.PositiveIntegerField(default=5, help_text='Nombre de témoignages à afficher')),
            ],
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ElementMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre du menu')),
                ('url_externe', models.CharField(blank=True, help_text='Laissez vide pour utiliser une page CMS', max_length=200, verbose_name='URL externe')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour masquer temporairement', verbose_name='Actif')),
                ('page_cms', models.ForeignKey(blank=True, help_text='Ou sélectionnez une page du site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Page CMS')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='core.elementmenu', verbose_name='Menu parent')),
            ],
            options={
                'verbose_name': 'Élément de menu',
                'verbose_name_plural': 'Éléments de menu',
                'ordering': ['parent__id', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
