# Generated by Django 4.2.7 on 2026-03-18 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#F97316', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='SlideTexteFondPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('sous_titre', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre')),
                ('texte', models.TextField(blank=True, verbose_name='Texte (HTML autorisé)')),
                ('bouton_texte', models.CharField(blank=True, max_length=50, verbose_name='Texte du bouton')),
                ('bouton_lien', models.CharField(blank=True, max_length=200, verbose_name='Lien du bouton')),
                ('hauteur', models.CharField(default='600px', help_text='Ex: 600px, 80vh, 100%', max_length=20, verbose_name='Hauteur du slide')),
                ('image_fond', filer.fields.image.FilerImageField(blank=True, help_text='Image qui sera affichée en arrière-plan', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Image de fond')),
            ],
            options={
                'verbose_name': 'Slide texte avec fond',
                'verbose_name_plural': 'Slides texte avec fond',
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_court_L1', models.CharField(default='République du Niger', max_length=40, verbose_name='Nom court (Première ligne)')),
                ('nom_court_L2', models.CharField(default="Ministère de l'Enseignement et de la", max_length=40, verbose_name='Nom court (Deuxième ligne)')),
                ('nom_court_L3', models.CharField(default='Formation Techniques et Professionnels', max_length=40, verbose_name='Nom court (Troisième ligne)')),
                ('nom_complet', models.CharField(default="Ministère de l'Enseignement et de la Formation Techniques et Professionnels", max_length=200, verbose_name='Nom complet')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Logo du site',
                'verbose_name_plural': 'Logos du site',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('chapeau', models.TextField(blank=True, max_length=300)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(blank=True, max_length=100)),
                ('auteur', models.CharField(blank=True, max_length=100)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_a_la_une', models.BooleanField(default=False)),
                ('vue_count', models.IntegerField(default=0)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.articlecategorie')),
                ('image_principale', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_principal', to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication', '-est_a_la_une'],
            },
        ),
    ]
