# Generated by Django 5.0.14 on 2026-03-11 09:13

import django.db.models.deletion
import django.utils.timezone
import filer.fields.file
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_alter_pageurl_unique_together_pageurl_site_and_more'),
        ('core', '0001_initial'),
        ('filer', '0017_image__transparent'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('couleur', models.CharField(default='#F97316', help_text='Code hexadécimal (ex: #F97316)', max_length=7)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('chapeau', models.TextField(blank=True, max_length=300)),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_evenement', models.DateTimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=100)),
                ('auteur', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=200)),
                ('est_publie', models.BooleanField(default=True)),
                ('est_a_la_une', models.BooleanField(default=False)),
                ('vue_count', models.IntegerField(default=0)),
                ('document_joint', filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.file')),
                ('galerie_images', models.ManyToManyField(blank=True, related_name='articles', to=settings.FILER_IMAGE_MODEL)),
                ('image_principale', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_principal', to=settings.FILER_IMAGE_MODEL)),
                ('page_liee', models.ForeignKey(blank=True, help_text='Page CMS associée (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.articlecategorie')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication', '-est_a_la_une'],
            },
        ),
    ]
