# Generated by Django 5.0.14 on 2026-03-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articlecategorie_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='testimonialplugin',
            name='cmsplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date_evenement',
        ),
        migrations.RemoveField(
            model_name='article',
            name='document_joint',
        ),
        migrations.RemoveField(
            model_name='article',
            name='galerie_images',
        ),
        migrations.RemoveField(
            model_name='article',
            name='page_liee',
        ),
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AlterField(
            model_name='articlecategorie',
            name='couleur',
            field=models.CharField(default='#F97316', max_length=7),
        ),
        migrations.DeleteModel(
            name='ElementMenu',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='TestimonialPlugin',
        ),
    ]
