# Generated by Django 5.0.14 on 2026-03-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_testimonial_image_and_more'),
        ('core', '0005_fix_vision_placeholder'),
    ]

    operations = [
    ]
