# Generated by Django 5.0.14 on 2026-03-12 14:07

import django.db.models.deletion
import filer.fields.image
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260311_1320'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_court', models.CharField(default='MEFTP', max_length=50)),
                ('nom_complet', models.CharField(default="Ministère de l'Enseignement et de la Formation Techniques et Professionnels", max_length=200)),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Logo du site',
                'verbose_name_plural': 'Logos du site',
            },
        ),
    ]
