# Generated by Django 5.0.14 on 2026-03-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='nom_complet',
            field=models.CharField(default="Ministère de l'Enseignement et de la Formation Techniques et Professionnels", max_length=200, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='logo',
            name='nom_court',
            field=models.CharField(default="République du Niger\nMinistère de l'Enseignement et de la\nFormation Techniques et Professionnels", help_text='Utilisez \\n pour créer un saut de ligne (ex: M\\nE\\nFTP)', max_length=100, verbose_name='Nom court (utilisez \\n pour les sauts de ligne)'),
        ),
    ]
