# Generated by Django 5.0.14 on 2026-03-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_logo_nom_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='logo',
            name='nom_court_L1',
            field=models.CharField(default='République du Niger', max_length=40, verbose_name='Nom court (Première ligne)'),
        ),
        migrations.AddField(
            model_name='logo',
            name='nom_court_L2',
            field=models.CharField(default="Ministère de l'Enseignement et de la", max_length=40, verbose_name='Nom court (Deuxième ligne)'),
        ),
        migrations.AddField(
            model_name='logo',
            name='nom_court_L3',
            field=models.CharField(default='Formation Techniques et Professionnels', max_length=40, verbose_name='Nom court (Troisième ligne)'),
        ),
    ]
