# Generated by Django 5.0.14 on 2026-03-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_logo_nom_court_l1_logo_nom_court_l2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='nom_court',
        ),
    ]
